name: Build Application
on:
  push:
    branches:
      - main
jobs:
  build-macos-exe:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
      - name: Install dependencies
        run: >
          poetry config virtualenvs.create false &&
          poetry install --no-interaction --no-root
      - name: Make App Executable Directory
        run: >
          mkdir -p excecutables/
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'main.py'
          upload_exe_with_name: 'tek-plexor-osx'
          options: --onefile, --name "TekPlexor", --windowed
      - name: Add Executable to Artifact Directory
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/main
