name: Build Application
on:
  push:
    branches:
      - main
jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
      - name: Install dependencies
        run: >
          poetry config virtualenvs.create false &&
          poetry install --no-interaction --no-root
