name: Build Application
on:
  push:
    branches:
      - main
jobs:
  build-macos-exe:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
      - name: Install dependencies
        run: >
          poetry config virtualenvs.create false &&
          poetry install --no-interaction --no-root
      - name: Create Executable
        run: >
          pyinstaller --onefile --windowed main.py -n tek_plexor.exe
      - name: see dir
        run: >
          cd dist && ls
      - name: Add Executable to Artifact Directory
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/tek_plexor.exe
